---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: d225e7e
_src_path: ./
description: Protocol Buffers API example 📜
docs: true
docsurl: https://quickplates.github.io/protobuf-example
projectname: protobuf-example
username: quickplates
