# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: c12aea6
_src_path: ./
accountname: quickplates
description: Protocol Buffers API example 📜
docs: true
docsurl: https://quickplates.github.io/protobuf-example
projectname: protobuf-example
releases: true
reponame: protobuf-example
repourl: https://github.com/quickplates/protobuf-example
