---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 98d0549
_src_path: ./
description: Protocol Buffers API example 📜
docs: true
docsurl: https://quickplates.github.io/protobuf-example
projectname: protobuf-example
username: quickplates
